spring.application.name=pickup-service
spring.data.mongodb.uri=mongodb+srv://admin:QWEasd123@wastemanagement.2nxwoyx.mongodb.net/waste-management?retryWrites=true&w=majority&appName=WasteManagement
server.port=8082
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.enabled=true
eureka.instance.lease-renewal-interval-in-seconds=30
eureka.instance.lease-expiration-duration-in-seconds=90
