spring.application.name=analytics-service
server.port=8083
spring.data.mongodb.uri=mongodb+srv://admin:QWEasd123@wastemanagement.2nxwoyx.mongodb.net/waste-management?retryWrites=true&w=majority&appName=WasteManagement

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
